apiVersion: siebel.metacontroller.io/v1alpha1
kind: Monitor
metadata:
  name: config-scmvanilla-4cgrfq-siebel-monitor
  namespace: config-scmvanilla-4cgrfq
spec:
  sourceName: config-scmvanilla-4cgrfq-siebel-checksum
  sourceNamespace: config-scmvanilla-4cgrfq
  deployment_type: CRM
