apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: config-scmvanilla-ui18zm
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: config-scmvanilla-ui18zm
    namespace: config-scmvanilla-ui18zm
  path: ./FluxFolder/infrastructure
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nginx
      namespace: config-scmvanilla-ui18zm