apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: scmvadbcs
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: scmvadbcs
    namespace: scmvadbcs
  path: ./FluxFolder/infrastructure
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nginx
      namespace: scmvadbcs