apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metacontroller
  namespace: config-scmvanilla-4cgrfq
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: config-scmvanilla-4cgrfq
    namespace: config-scmvanilla-4cgrfq
  path: ./FluxFolder/metacontroller
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metacontroller
      namespace: config-scmvanilla-4cgrfq