apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: siebel-operator
  namespace: config-scmvanilla-4cgrfq
spec:
  interval: 10m0s
  dependsOn:
    - name: metacontroller
  sourceRef:
    kind: GitRepository
    name: siebel-repo
    namespace: config-scmvanilla-4cgrfq
  path: ./siebel-operator
  targetNamespace: config-scmvanilla-4cgrfq
  prune: true